### PR TITLE
Code cleanup, release 0.1.6

### LINKED ISSUE #4: Release latest version
Thanks for updated fork, can you release latest version and push it to Cocoapods?

### PR DESCRIPTION
**Pull request by ealeksandrov**
No big changes in code, just cleanup and updating CocoaPods.
Podspec updated to 0.1.6, so please just run `pod trunk push` after merging and pulling to your machine.

Will resolve #4 and #5.

### CODE REVIEW

**Comment by ealeksandrov** [comment]
@shmidt when you have a free minute, please merge this PR and release latest version to CocoaPods.

**Comment by shmidt** [comment]
Thank you very much, Evgeny.

**Comment by shmidt** [comment]
@ealeksandrov Great job, Evgeny. 
Thanks a lot, pod was updated today.
What do you think if I'll transfer this repo to you?

**Comment by ealeksandrov** [comment]
No problem. I don't think this is needed, I can push to master now and some projects podfiles already pointed on your github URL. Lets keep them working :)

Thanks for releasing!

**Pull request merged**
