### PR TITLE
Swift 4 upgrade and complete refactor for reference

### PR DESCRIPTION
**Pull request by basememara**
Thanks for your head start from the original repo!

### CODE REVIEW

**Comment by ealeksandrov** [comment]
Thanks!
1. It would be perfect to make 0.1.8 as just "Swift 4 update" and then 0.2.0 as "MapKit support + deployment target bump". In that case we 0.1.8 version commit *before* commits related to MapKit and 0.2.0. You can put them in single PR with no problem, I'll add 2 tags/releases.
Right now commits are:
- swift 4
- MapKit fallback
- fix demo project and bump deployment target and bump version to 0.1.8

What I want:
- swift 4
- fix demo project
- bump pod version to 0.1.8  <- 1st release will be here
- MapKit fallback
- bump deployment target to iOS 9
- bump pod version to 0.2.0 <- 2nd release

You can remove all MapKit stuff now and create new PR for 0.2.0 later to keep things simple if you want :)

2. You bumped deployment target straight to 10.3. Is it needed? Errors above was showing only 9.3 requirement.

**Comment by bbookman** [comment]
Sorry for the dumb question, but HOW do i get the swift 4 version of GooglePlacesSearchController ? The  docs (which seem copied from  ios_google_places_autocomplete) still say Swift3.

**Comment by ealeksandrov** [comment]
@bbookman 
you can try linking directly to https://github.com/basememara/GooglePlacesSearchController/tree/swift4 in your Podfile.

I'll dedicate some time later this week to get swift 4 support merged.

**Comment by david-var** [comment]
Hi, any updated for Swift 4?

**Comment by ealeksandrov** [comment]
@basememara @bbookman @david-var 
Swift 4 update released as [0.2.0](https://github.com/shmidt/GooglePlacesSearchController/releases/tag/0.2.0).

@shmidt please push 0.2.0 release to CocoaPods when you have time.

@basememara thanks for contribution! I cherry-picked your https://github.com/shmidt/GooglePlacesSearchController/commit/661aa85108371f78083370031217b7c4847d58b2 into master. If you want MapKit fallback merged into next release - please create new PR from master.

**Comment by shmidt** [comment]
@ealeksandrov. Thanks, will do it on Monday.

**Pull request closed without merging**
